spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courses
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: UTC
      globally_quoted_identifiers: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9191